[workspace]
resolver = "2"
members = [
  "identity_agent",
  # "identity_comm",
  "identity_core",
  "identity_credential",
  "identity_did",
  "identity_diff",
  "identity_iota",
  "identity_iota_core",
  "identity_resolver",
  # TODO: Remove
  "identity_storage",
  # TODO: Rename to `identity_storage`
  "identity_key_storage",
  "identity_data_integrity",
  "examples",
]

exclude = [
  "identity_iota_core_legacy",
  "bindings/stronghold-nodejs",
  "bindings/wasm",
  "libjose",
]

[profile.dev]
split-debuginfo = "unpacked"
