[package]
name = "identity-actor"
version = "0.1.0"
authors = ["IOTA Stiftung"]
edition = "2018"
homepage = "https://www.iota.org"
keywords = ["iota", "tangle", "identity"]
license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
description = "A peer-to-peer identity communication framework"

[dependencies]
async-trait = "0.1.50"
dashmap = "4.0"
futures = "0.3"
identity-account = { path = "../identity-account", default-features = false, optional = true }
identity-core = { path = "../identity-core" }
identity-did = { path = "../identity-did" }
identity-iota = { path = "../identity-iota", default-features = false }
libp2p = { version = "0.39", default-features = false, features = ["tcp-async-io"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.7", features = ["rt"] }
uuid = { version = "0.8", features = ["v4"] }

[dependencies.stronghold-p2p-refactored]
git = "https://github.com/iotaledger/stronghold.rs"
rev = "d93c9f632bbcba336ae70e2b18b86e0e286b5111"
default-features = false

[dev-dependencies]
anyhow = "1.0"
pretty_env_logger = "0.4.0"

[features]
account = ["identity-account/default"]
wasm = ["identity-iota/wasm", "identity-account/wasm", "uuid/wasm-bindgen"]
tcp = ["stronghold-p2p-refactored/tcp-transport"]
websocket = ["libp2p/websocket"]
default = ["account", "tcp", "websocket"]
