[package]
name = "identity_validator"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
identity_did = { path = "../identity_did" }
identity_credential = { path = "../identity_credential" }
identity_iota_core = { path = "../identity_iota_core", features = ["iota-client"] }
identity_jose = { path = "../identity_jose" }
identity_verification = { path = "../identity_verification" }
identity_eddsa_verifier = { path = "../identity_eddsa_verifier", features = ["ed25519"] }
iota-sdk = { version = "1.1.4", features = ["client"] }
thiserror.workspace = true