[package]
name = "identity_data_integrity_types"
version = "0.7.0-alpha.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
