[package]
name = "identity-wasm"
version = "0.5.0-dev.4"
authors = ["IOTA Stiftung"]
edition = "2021"
homepage = "https://www.iota.org"
keywords = ["iota", "tangle", "identity", "wasm"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/iotaledger/identity.rs"
resolver = "2"
description = "Web Assembly bindings for the identity-rs crate."

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = { version = "0.1" }
futures = { version = "0.3" }
js-sys = { version = "0.3" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false }
serde_repr = { version = "0.1", default-features = false }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = { version = "0.4", default-features = false }
once_cell = "1.8.0"
log = "0.4.6"
wasm-logger = "0.2.0"

[dependencies.tokio]
version = "1.7"
default-features = false
features = ["rt"]

[dependencies.identity]
version = "=0.5.0-dev.4"
path = "../../identity"
default-features = false

[dependencies.libp2p]
version = "0.39"
default-features = false
features = ["wasm-bindgen", "wasm-ext", "websocket", "wasm-ext-websocket"]

[patch.crates-io]
libp2p = { path = "../../../rust-libp2p" }
wasm-timer = { path = "../../../wasm-timer" }

[dev-dependencies]
wasm-bindgen-test = { version = "0.3" }

[target.'cfg(all(target_arch = "wasm32", not(target_os = "wasi")))'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
parking_lot = { version = "0.11.2", features = ["wasm-bindgen"] }
# Also use JavaScript randomness APIs for v0.1.X, where this feature is called wasm-bindgen.
getrandom01 = { package = "getrandom", version = "0.1", features = ["wasm-bindgen"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = true

[profile.release]
opt-level = 's'
lto = true
